version: '3.7'
services:
  app:
    build:
      context: .
    image: subway-api
    container_name: subway-api
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: subway-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data: